# Generated by Django 4.2.13 on 2024-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Services categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Имя', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
