# Generated by Django 4.2.13 on 2024-07-08 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 15, 29, 34, 619812)),
        ),
        migrations.AddField(
            model_name='application',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
