# Generated by Django 4.2.13 on 2024-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_time_create_application_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_update',
            field=models.DateTimeField(null=True),
        ),
    ]
