# Generated by Django 4.2.13 on 2024-07-13 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_alter_application_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
