# Generated by Django 4.2.13 on 2024-07-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='experience_years',
            field=models.FloatField(default=0.0, verbose_name='Лет опыта'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
    ]
